### ISSUE TITLE
Pre-trained weights download link 404s 🛑

### ISSUE THREAD

**Issue by juniorxsound** [vt-vl-lab/Guided-pix2pix#1]
*What?*
The pre-trained checkpoints [download link in the README 404s](https://filebox.ece.vt.edu/~Badour/datasets/guided_pix2pix_checkpoints/pretrained.zip)

**Comment by BadourAlBahar** [comment]
Fixed.

**Comment by juniorxsound** [comment]
For future reference, the [download link is now here](https://filebox.ece.vt.edu/~Badour/guided_pix2pix_checkpoints/pretrained.zip)
