### ISSUE TITLE
About the link of pkl format of pose dataset

### ISSUE THREAD

**Issue by Huage001** [vt-vl-lab/Guided-pix2pix#10]
Hi, thank you for your wonderful contribution!

I recently found that the link of pkl format of the pose dataset [here](https://filebox.ece.vt.edu/~Badour/datasets/DeepFashion.zip) is failed. Could you please re-share the file and update the link?

Thanks a lot for your help:)

**Comment by BadourAlBahar** [comment]
Thank you very much for your interest in our work.
Please note that unfortunately we are unable to continue maintaining that file due to its considerable size.
Please check out [this issue](https://github.com/vt-vl-lab/Guided-pix2pix/issues/8#issuecomment-694272052) for an alternative solution.
