### ISSUE TITLE
Why beta1 0.9 in Adam for Guided pix2pix while 0.5 for pix2pix?

### ISSUE THREAD

**Issue by franciszchen** [vt-vl-lab/Guided-pix2pix#2]
Excuse me, when reading the paper, I am curious why different settings on beta1 in Adam, as described in Section 4. Is there any trick? What about setting them both 0.9? Thanks~

**Comment by BadourAlBahar** [comment]
No really. During experimentation we found that for some experiments using beta1 as 0.9 resulted in a more stable training. 
You can test with both parameters and see if it makes a difference.
