### ISSUE TITLE
depth test output image

### ISSUE THREAD

**Issue by tsian077** [vt-vl-lab/Guided-pix2pix#3]
hello!! i want to ask the depth output image look like this is correct?i am confuse that it isn't look like with target. i use the pretrain model  ![image](https://imgur.com/IEfyguE.png)

**Comment by BadourAlBahar** [comment]
For the first sample, it should look like this:
![depth_sample](https://user-images.githubusercontent.com/26908117/74106056-5339d080-4b31-11ea-8d40-cae66487120b.png)

**Comment by tsian077** [comment]
Thanks! i will figure out what happen on my environment :DD
