### ISSUE TITLE
question about data

### ISSUE THREAD

**Issue by xcc13** [vt-vl-lab/Guided-pix2pix#7]
Hello~
Did you use paird guiding images and source domain images for training?
I want to use  my own data to train this network, but I don't know how to prepare the guieded image.

**Comment by BadourAlBahar** [comment]
It depends on the task. For example, in texture transfer you would take an image X get the **sketch** as **input** and sample a **texture patch** as **guidance** and the **target** ground truth is the image **X**.

**Comment by xcc13** [comment]
> It depends on the task. For example, in texture transfer you would take an image X get the sketch as input and sample a texture patch as guidance and the target ground truth is the image X.

Thanks for your reply. 
Does this mean that each sketch has its own guided image during training？

**Comment by BadourAlBahar** [comment]
Yes. For every sketch we would sample a random sized patch from a random location of the GT image.
