### ISSUE TITLE
about pose transfer dataset size

### ISSUE THREAD

**Issue by kmaeii** [vt-vl-lab/Guided-pix2pix#8]
Hi,
I want to train the pose transfer use the dataset you provided( [here](https://filebox.ece.vt.edu/~Badour/datasets/DeepFashion.zip)). But when i unzip the dataset, i find it size about 3T. My server does not have such a large memory. So, when you train the pose transfer task, did you use the entire dataset?

**Comment by BadourAlBahar** [comment]
Yes, I did use the entire dataset. To insure fair comparison with state of the art at that time, I have generated the data in pkl format from the tf-record format provided [here](https://github.com/charliememory/Disentangled-Person-Image-Generation).  
You can instead however use the raw data. An alternative approach is to follow the data preprocessing in [PATN](https://github.com/tengteng95/Pose-Transfer).
